config/routes.rb
Rails.application.routes.draw do

  get 'secret/index'

  get 'main/index'
  get 'search' => 'main#index', as: :search
  get 'newCall' => 'main#newCall', as: :newCall
  get 'validations' => 'validations'
  get 'settings' => 'settings#index', as: :settings
  get "downloadPRC" => 'settings#downloadPRC', as: :downloadPRC
  get "changePassword" => 'settings#change', as: :passwordForm

  post "changePassword" => 'settings#change', as: :changePassword

  post 'clear_form' => 'main#clear_form', as: :clear_form
  post 'newCall' => 'main#newCall'
  post 'submit_form' => 'main#submit_form'

  root 'main#index'
  resources :items
  resources :counties
  resources :item_counties
  resources :item_locations
  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

#Changing password
  def change
    #Checks that a username and password have been inputted into form
    if params[:user] and params[:password]
      #Connects to DropboxApi to upload a new file, credentials.csv, with user and password written in
      client = DropboxApi::Client.new
      file_content = "#{params[:user]},#{params[:password]}"
      client.upload "/credentials.csv", file_content, :mode => :overwrite
      redirect_to settings_path, notice: 'Password settings were successfully updated.'
    end
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/change.html.erb
<div class="row">
  <h2>Change Password</h2>
  <div class="form">
    <%= form_tag(changePassword_path) do |f| %>
    Enter Username
    <%= text_field_tag :user %>
    Enter Password
    <%= text_field_tag :password %>
    <%= submit_tag "Submit", class: "button" %>
    <%= link_to 'Back', settings_path, class: "button" %>
    <% end %>
  </div>
</div>

app/views/settings/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <h2>System Settings</h2>
  <h4>Database</h4>
  <div class="large-6 columns">
    <h4>Counties & Coordinators</h4>
    <%= link_to "View All", counties_path, class: "button" %>
    <%= link_to "Add", new_county_path, class: "button" %>
    <br>
  </div>

  <div class="large-6 columns">
    <div class="panel">
      <h4>Items</h4>
      <%= link_to "View All", items_path, class: "button" %>
      <%= link_to "Add", new_item_path, class: "button" %>
      <br>
    </div>
  </div>
  <hr>


  <h4>System Password</h4>
  <%= link_to 'Change', passwordForm_path, class: "button" %>
  <hr>


    <h4>Export Call Reports</h4>

    <%= link_to 'Download Monthly Reports', "https://www.dropbox.com/sh/d8ut1o61gadwt3w/AAADJk3qsdy97VgdTejtS035a?dl=0",target: :_blank, class: "button" %>


</div>