config/routes.rb
Rails.application.routes.draw do

  get 'secret/index'

  get 'main/index'
  get 'search' => 'main#index', as: :search
  get 'newCall' => 'main#newCall', as: :newCall
  get 'validations' => 'validations'
  get 'settings' => 'settings#index', as: :settings
  get "downloadPRC" => 'settings#downloadPRC', as: :downloadPRC
  get "changePassword" => 'settings#change', as: :passwordForm

  post "changePassword" => 'settings#change', as: :changePassword

  post 'clear_form' => 'main#clear_form', as: :clear_form
  post 'newCall' => 'main#newCall'
  post 'submit_form' => 'main#submit_form'

  root 'main#index'
  resources :items
  resources :counties
  resources :item_counties
  resources :item_locations
  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :item_locations, dependent: :destroy
  has_many :item_counties, dependent: :destroy
  has_many :counties, through: :item_counties
  has_many :locations, through: :item_locations
  has_many :addresses, through: :locations
  has_many :aliases, dependent: :destroy

  validates_presence_of :name


  accepts_nested_attributes_for :aliases, reject_if: lambda { |attraction| attraction[:name].blank? }, allow_destroy: true


  scope :alphabetical, -> { order('name') }




  scope :for_name, -> (name) { where("name=?", name) }

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    # This search is used for all item autocompletes
    if params[:term]
      # Tries to string match all the items with the search term
      # Limit here is 10 so as to not overflow the page with autocomplete
      @items = Item.where("name ilike ?", "%#{params[:term]}%").limit(10)
      arr = []
      # adds possible counties into an array of options to select
      @items_autocomplete = @items.map do |i|
        arr.push(i.name)
      end
      respond_to do |format|
        format.json { render :json => @items_autocomplete[0]}
      end
      return
    else
      @items = Item.alphabetical.all.paginate(:page => params[:page]).per_page(20)
      respond_to do |format|
        format.html
        format.json { render json: ItemDatatable.new(view_context) }
      end
      return
    end

  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    # Accepts aliases as a nested form
    @item.aliases.build
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :active, aliases_attributes: [:id, :name, :_destroy])
    end
end

app/views/items/_alias_field.html.erb
<div class="fields">
  <div class="row">
    <div class="large-4 columns">
      <%= f.input :name %>
    </div>
    <div class="large-8 columns">
      <%= f.link_to_remove("x") %>
    </div>
  </div>
</div>

app/views/items/_form.html.erb
<%= simple_nested_form_for @item, :html => { :class => 'form-horizontal' } do |item_form| %>


  <% if item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(item.errors.count, "error") %>
      prohibited this item from being saved:</h2>
    <ul>
      <% item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <%= render :partial => "item_form", :locals => { :f => item_form } %>

  <legend>Aliases for this item:</legend>
  <div id="item_aliases">
    <%= item_form.simple_fields_for :aliases do |alias_form| %>
    <%= render :partial => "alias_field", :locals => { :f => alias_form } %>
    <% end %>
    <p>
      <br/><%= item_form.link_to_add("Add alias", :aliases, :class => 'button tiny') %>
    </p>

  </div>

  <div class="form-actions">
    <br/>
    <%= item_form.submit nil, :class => 'button radius' %>
    <%= link_to 'Cancel', items_path, :class => 'button secondary' %>
  </div>

<% end %>

app/views/items/_item_form.html.erb
<%= f.input :name %>
<%= f.input :description %>

app/views/items/edit.html.erb
<div class="large-12 columns">
  <div class="panel callout radius">
    <h2>Editing Item</h2>
    <%= render 'form', item: @item %>
  </div>
</div>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>
<script>
  items_table = null
  $(document).on('turbolinks:load', function () {
    items_table = $('#items-table').DataTable({
      "destroy": true,
      "processing": true,
      "serverSide": true,
      "ajax": $('#items-table').data('source'),
      "pagingType": "full_numbers",
      "iDisplayLength": 75,
      "bLengthChange": false,
      //Check dataTables documentation to learn more about available options such as optional pagination controls.
    });

  })
  $(document).on('turbolinks:before-cache', function () {
    if ($.fn.dataTable.isDataTable('#items-table')) {
      items_table.destroy();
    }
  })
</script>


<div class="row">


    <div class="large-2 columns">
      <h1>Items</h1>
    </div>

    <div class="large-2 columns">
      <br/>
    <%= link_to 'Add Item', new_item_path, :class => "button" %>
    </div>


</div>

<div class="column row">
  <div class="large-12 columns">
    <div class="panel">
      <% if @items.blank? %>

        <h4>No item available.</h4>
      <% else %>
        <table id="items-table" data-source="<%= items_path(format: :json) %>">
          <thead>
            <tr>
              <th>Name</th>
              <th data-sortable="false">Description</th>
              <th data-sortable="false">Aliases</th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
      <% end %>
      <br>

    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="large-12 columns">
  <div class="panel callout radius">
    <h2>New Item</h2>
    <%= render 'form', item: @item %>
  </div>
</div>

app/views/items/show.html.erb
<div class="large-8 large-centered columns">
  <div class="panel callout radius">
    <p id="notice"><%= notice %></p>

    <h3><%= @item.name.titleize %></h3>

    <% if @item.aliases.size > 0 %>

      <p>
        <strong>Aliases</strong>
        <% @item.aliases.each do |a| %>
          <li><%=  a.name %></li>
        <% end %>
      </p>
    <% else %>
      <p>
        <strong>No Aliases</strong>
      </p>

    <% end %>

    <p>
      <strong>Description:</strong>
      <%= @item.description %>
    </p>

    <div class="row">
      <%= link_to 'Edit', edit_item_path(@item), class: "button" %>
      <%= link_to 'See All', items_path, class: "button" %>
      <%= link_to 'Delete', item_path(@item), method: 'delete', class: "alert button" %>
    </div>

  </div>
</div>