config/routes.rb
Rails.application.routes.draw do

  get 'secret/index'

  get 'main/index'
  get 'search' => 'main#index', as: :search
  get 'newCall' => 'main#newCall', as: :newCall
  get 'validations' => 'validations'
  get 'settings' => 'settings#index', as: :settings
  get "downloadPRC" => 'settings#downloadPRC', as: :downloadPRC
  get "changePassword" => 'settings#change', as: :passwordForm

  post "changePassword" => 'settings#change', as: :changePassword

  post 'clear_form' => 'main#clear_form', as: :clear_form
  post 'newCall' => 'main#newCall'
  post 'submit_form' => 'main#submit_form'

  root 'main#index'
  resources :items
  resources :counties
  resources :item_counties
  resources :item_locations
  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/partials/_floatingForm.erb
<h3>New Call</h3>
<%= form_tag("/submit_form", method: "post") do %>
<!-- All of the form inputs take @val value if available, otherwise take default value -->
County
<%= select_tag 'county', options_for_select(County.all.alphabetical.map { |a| [a.name, a.id]}, @vals[0]), prompt:"Select a county", :required => true %>

Item
<%= select_tag 'item', options_for_select(Item.all.alphabetical.map { |a| [a.name.capitalize, a.id]}, @vals[1]), prompt:"Select an item", :required => true %>

Caller Name
<%= text_field_tag :callerName, @vals[2], placeholder: "Enter caller name" %>

How did you find out about the hotline?
<script type="text/javascript">
  function showfield2(name) {
    // Each of these showfield methods is used to add the Other option text field when chosen
    if (name == 'other2')
      document.getElementById('div2').innerHTML = 'Other method: <input type="text" name="altOther2" />';
    else
      document.getElementById('div2').innerHTML = '';
    }
    // This fuction is used to identify the selected value in the possible options for Method
  $(function () {
    var mySelect = document.getElementById('method');
    for (var i, j = 0; i = mySelect.options[j]; j++) {
      if (i.value == "<%= @vals[3]%>") {
        mySelect.selectedIndex = j;
        break;
      }
    }
  });
</script>

<select required name="method" id="method" onchange="showfield2(this.options[this.selectedIndex].value)">
  <option value="" disabled selected>Select the method</option>
  <option value="Flyer">Flyer</option>
  <option value="Hauler">Hauler</option>
  <option value="Internet">Internet</option>
  <option value="Municipality">Municipality</option>
  <option value="Recycling Center">Recycling Center</option>
  <option value="Verizon">Verizon</option>
  <option value="other2">Other</option>
</select>
<div id="div2"></div>

What was the disposition?
<script type="text/javascript">
  function showfield3(name) {
    if (name == 'other3')
      document.getElementById('div3').innerHTML = 'Referred to Other: <input type="text" name="altOther3" />';
    else if (name == 'directly')
      document.getElementById('div3').innerHTML = 'Answered Directly: <input type="text" name="directly" />';
    else
      document.getElementById('div3').innerHTML = '';
    }
  $(function () {
    var mySelect1 = document.getElementById('disposition');
    for (var i, j = 0; i = mySelect1.options[j]; j++) {
      if (i.value == "<%= @vals[4]%>") {
        mySelect1.selectedIndex = j;
        break;
      }
    }
  });
</script>

<select required name="disposition" id="disposition" onchange="showfield3(this.options[this.selectedIndex].value)">
  <option value="" disabled selected>Select the disposition</option>
  <option value="Referred to Verizon">Referred to Verizon</option>
  <option value="Referred to County Coordinator">Referred to County Coordinator</option>
  <option value="Referred to CDRA Manufacturer">Referred to CDRA Manufacturer</option>
  <option value="Referred to DEP">Referred to DEP</option>
  <option value="directly">Answered Directly</option>
  <option value="other3">Referred to Other</option>
</select>
<div id="div3"></div>

What was the call type?
<script type="text/javascript">
  function showfield(name) {
    if (name == 'Other')
      document.getElementById('div1').innerHTML = 'Other type: <input type="text" name="altOther" />';
    else
      document.getElementById('div1').innerHTML = '';
    }
  $(function () {
    var mySelect2 = document.getElementById('callType');
    for (var i, j = 0; i = mySelect2.options[j]; j++) {
      if (i.value == "<%= @vals[5]%>") {
        mySelect2.selectedIndex = j;
        break;
      }
    }
  });
</script>

<select required name="callType" id="callType" onchange="showfield(this.options[this.selectedIndex].value)">
  <option value="" disabled selected>Select the call type</option>
  <option value="Where to recycle">Where to recycle?</option>
  <option value="How to recycle">How to recycle?</option>
  <option value="Why can't I recycle?">Why can't I recycle?</option>
  <option value="Verizon Inquiry">Verizon Inquiry</option>
  <option value="Other">Other</option>
</select>
<div id="div1"></div>

Call for
<br>
<%= radio_button_tag(:callFor, "PRC", if @vals[6] == "PRC" then true end) %>
<%= label_tag(:callFor_prc, "PRC") %>

<%= radio_button_tag(:callFor, "DEP", if @vals[6] == "DEP" then true end) %>
<%= label_tag(:callFor_dep, "DEP") %>
<br>

<%= submit_tag "Submit", name: 'submit_clicked', class: "button" %>
<%= submit_tag "Save", class: "button" %>

<% end %>
<%= button_to 'Clear', clear_form_path, method: :post, class: "button secondary" %>

app/views/layouts/partials/_header.html.erb
<script>
  $(function () {
    $("#counties").autocomplete({source: '<%= counties_path(:json) %>'});
    $("#items").autocomplete({source: '<%= items_path(:json) %>'});
  });
</script>

<div class="top-bar">
  <div class="top-bar-title">
    <class="name"><%= link_to image_tag("logo.jpg", size: "70x70"), search_path, class: "active" %>

    </div>
    <div id="responsive-menu">
      <div class="top-bar-left">
        <div class="row">
          <div class="medium-3 columns">
            <h4><%= link_to "Locations", locations_path%></h4>
          </div>
        </div>
      </div>
      <div class="top-bar-right">
        <ul class="menu">

          <%= form_tag("/search", :method => "get", id: "search-form") do %>
          <div class="row">
            <div class="medium-3 columns">
              <%= text_field_tag :county, params[:county], :placeholder => 'Enter County', id:'counties' %>
            </div>
            <div class="medium-3 columns">
              <%= text_field_tag :item, params[:item], :placeholder => 'Item (Optional)', id:'items' %>

            </div>
            <div class="medium-3 columns">
              <%= text_field_tag :zip, params[:zip], placeholder: "Zip (Optional)", maxlength: 5, class: 'input-small'%>
            </div>
            <div class="medium-1 columns">
              <%= submit_tag "Search", :name => nil, class: "button" %>
            </div>
            <% end %>
            <div class="medium-2 columns">
              <h4><%= link_to "Settings", settings_path%>
              </h4>
            </div>
          </ul>

        </div>

      </div>
    </div>

app/views/layouts/partials/_searchResults.html.erb
<p id="notice"><%= notice %></p>

<div class="column expanded row" style="width: 80%">
  <div class="callout" align='center'>

    <h2><%= @item.name.capitalize %>
      in
      <%= @county.name %>
      County</h2>

    <% st = "" %>
    <% @item.aliases.each do |a| %>
    <% if a.name != @item.name %>
    <% st += " " + a.name %>
    <% end %>
    <% end %>
    <% if st != "" %>
    <h6>Also known as:
      <%= st %>
    </h6>
    <% end %>
    <br>

    <div class="large-7 columns" align='left'>
      <h4><%= @item.name.capitalize %></h4>

      <p><%= @item.description%></p>


    </div>

    <div class="large-5 columns" align='left'>
      <h4>County Specific Details</h4>
      <% i = ItemCounty.by_item(@item.id).by_county(@county.id).first %>
      <% if i == nil %>
      <% ItemCounty.create(:item_id => @item.id, :county_id => @county.id, :description => 'There is no information for this item in this county. Click to add.') %>
      <% i = ItemCounty.by_item(@item.id).by_county(@county.id).first %>
      <% end %>
      <%= best_in_place i, :description, :as => :textarea, :inner_class => "best_in_place"%>
      <br></br>
      <br></br>

      <h6>County Coordinator:</h6>
      <% if @county.coordinator != nil %>
      <%= @county.coordinator %><br>
    <% else %>
      <%= "There is no county coordinator." %><br>
      <% end %>
      <% if @county.coordinator != nil %>
      <%= @county.phone%><br>
    <% else %>
      <%= "There is no county phone." %><br>
      <% end %>
      <% link = @county.website%>
      <% if link != nil %>
      <%= link_to "County Recycling Website", "#{link}", :target => "_blank" %><br>
    <% else %>
      <%= "There is no county website." %><br>
      <% end %>
      <td><%= link_to 'Edit County Information', edit_county_path(@county) %></td>
    </p>
  </div>

  <br>

  <div align='center'>
    <%if @locations.size > 0 %>
    <table border="1px solid black">
      <thead>
        <tr>
          <th><%= button_to "by Name", search_path, method: :get, params: { :county => params[:county], :item => params[:item], :zip => params[:zip], :sortby => "name" }%></th>
          <th>Address</th>
          <th>Contact Info</th>
          <th width="10%"><%= button_to "by Verified", search_path, method: :get, params: { :county => params[:county], :item => params[:item], :zip => params[:zip], :sortby => "verified" }%></th>
          <th>Context</th>
          <th>Verify</th>
        </tr>
      </thead>

      <tbody>
        <% @locations.each_with_index do |addr, index| %>
        <tr>
          <% location = Location.find(addr.location_id) %>
          <td><%= link_to location.name, location%>
          </td>
          <td><%= link_to addr.full_address, "http://maps.google.com/?q=#{addr.full_address}", target: :_blank %>
          </td>
          <td>
            <%= link_to location.website, "#{location.link_to_website}", target: :_blank %>
            <br/>
            <% ph = location.phone %>
            <% a = location.phone.gsub!(/\D/, "") %>
            <%= "(#{ph[0..2]})" %>&nbsp;<%="#{ph[3..5]}"%>&nbsp;<%="#{ph[6..-1]}"%>
          </td>

          <td>
            <em>
            <%= if location.active then "Active" else "Inactive" end %>
            </em><br/>
            Updated<br/>
            <% if (Time.new.to_date - location.updated_at.to_date).to_i < 0%>
            0 days ago
            <% elsif (Time.new.to_date - location.updated_at.to_date).to_i == 1 %>
            1 day ago
          <% else %>
            <%= (Time.new.to_date - location.updated_at.to_date).to_i %>
            days ago
            <% end %>
          </td>

          <td>
            <%= location.item_locations.first.context %>
          </td>
          <td>
            <%= simple_nested_form_for location, :html => { :class => 'form-horizontal' } do |f| %>
            <%= f.input :verified, :as => :hidden, :input_html => { :value => Time.new.to_date } %>
            <%= f.submit "Verify", class: "button radius" %>
            <% end %>
          </td>

        </tr>
        <% end %>
      </tbody>

    </table>
  <% else %>
    <%= "There are no active locations where this item can be recycled." %>
    <% end %>
  </div>

</div>

</div>

<% if @locations != [] %>
<%= will_paginate @locations, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
<% end %>

app/views/layouts/partials/_validations.html.erb
<p id="notice"><%= notice %></p>
<h4>
  <%= @countyName %>
</h4>
<% @locations.each do |location| %>
<div class="row">
  <br/><br/>
</div>
<div class="row">
  <fieldset style="box-shadow: 0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23); padding: 10px 10px 10px 10px;">
    <%= simple_nested_form_for location, :html => { :class => 'form-horizontal' } do |location_form| %>

    <div class="row">
      <div class="large-6 column">
        <h4><%= location.name %></h4><br/>
      </div>
      <div class="large-3 small-3 column">
        <%= location.website %>
        <br/>
        <% ph = location.phone %>
        <% a = location.phone.gsub!(/\D/, "") %>
        <%= "(#{ph[0..2]})" %>&nbsp;<%="#{ph[3..5]}"%>&nbsp;<%="#{ph[6..-1]}"%>
      </div>
      <div class="large-2 small-1 column">
        <i>
          Updated
        </i>
        <br/>
        <% year = "#{location.updated_at.year}".split(//).last(2).join %>
        <%= "#{location.updated_at.month}/#{location.updated_at.day}/#{year}" %>

        <br/>
        <% if (Time.new.to_date - location.updated_at.to_date).to_i < 0%>

        0 days ago
      <% else %>
        <%= (Time.new.to_date - location.updated_at.to_date).to_i %>
        days ago
        <% end %>
      </div>
      <div class="large-1 small-1 column">
        <%= location_form.input :active, label: "",  as: :radio_buttons, :collection => [['Active', true],['Inactive', false]], :input_html => {  id: "active#{location.id}" }  %>

      </div>
    </div>
    <div class="row" style="padding-left: 15px;">
      Addresses:
      <br/>
      <%= location.addresses.first.address %>
      <%= location.addresses.first.city %>, PA
      <%= location.addresses.first.zipcode %>
      in
      <%= location.addresses.first.county.name %>
      &nbsp;&nbsp;
      <a data-open="<%=location.id%>AddressModal">More Addresses</a>
      <div class="reveal" id="<%=location.id%>AddressModal" data-reveal>

        <h3>
          <%= location.name %>
          Addresses
        </h3>
        <% @location = location %>
        No other addresses.

        <button class="close-button" data-close type="button">
          x
        </button>

      </div>
      <%= location_form.input :verified, :as => :hidden, :input_html => { :value => Time.new.to_date } %>

    </div>
    <br/>
    <div class="row">
      <div class="large-10 column">

        <% count = 1 %>
        <div class="row">
          <%= location_form.simple_fields_for :item_locations do |il| %>
          <%= render :partial => "locations/item_loc_active", :locals => { :l => il } %>
          <% if count % 5 == 0 %>
        </div>
        <div class="row">
          <% end %>
          <%= il.input :active, label: il.object.item.name, wrapper_html: { class: "large-2 column"}, input_html: { id: "itemcheck#{location.id}#{count}" }%>
          <% count += 1 %>
          <% end %>
        </div>

        <div class="reveal" id="<%=location.id%>Modal" data-reveal>

          <h3>
            <%= location.name %>
          </h3>
          <% @location = location %>

          <button class="close-button" data-close type="button">
            x
          </button>

        </div>

      </div>
      <div class="large-2 column">
        <%= link_to 'Edit', edit_location_path(location), target: :_blank %>

        <%= location_form.submit "Verify" %>
      </div>
    </div>
    <% end %>
  </fieldset>
</div>
<% end %>

app/views/layouts/partials/_validationsPartial.html.erb
<p id="notice"><%= notice %></p>

<h3> <%= @countyName %> </h3>





<table border= "1px solid black">
  <thead>
    <tr>
      <th>Location</th>
      <th>Items</th>
      <th>Context</th>
      <th>Website</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Last Verified</th>
      <th>Availability</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td>
          <ul>
            <% count=0 %>
            <% @item_locations.for_location(location.id).each do |il| %>
              <% count+=1 %>
              <% if count < 4 %>
                <li><%= il.item.name %></li>
              <% else %>
                <br></br>
                <a data-open= "<%=location.id%>Modal" >More...</a>


                <% break%>
              <% end %>
            <% end %>
            <div class="reveal" id="<%=location.id%>Modal" data-reveal>
              <h3> <%= location.name %> </h3>
              <form>
                <fieldset class="fieldset">
                  <legend>Items accepted here</legend>
                  <div class="row">

                    <% @item_locations.for_location(location.id).each do |il| %>
                      <input id= <%= location.name %> type="checkbox"><label for=<%= location.name %>><b><%= il.item.name %></b></label>

                    <% end %>

                  </div>
                </fieldset>
              </form>
              <button data-close> Confirm </button>
              <%= link_to 'Edit', edit_location_path(location) %>
              <button class="close-button" data-close aria-label="Close modal" type="button">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          </ul>
        </td>
        <td><%= 'Should we have something for this field?' %></td>
        <td><%= location.website %></td>

        <td>
          <% ph = location.phone %>
          <% a = location.phone.gsub!(/\D/, "") %>
          <%= "(#{ph[0..2]})" %>&nbsp;<%="#{ph[3..5]}"%>&nbsp;<%="#{ph[6..-1]}"%>
        </td>
        <td><%= location.address %></td>
        <td>
          <%= "#{location.updated_at.month}/#{location.updated_at.day}/#{location.updated_at.year}" %>

           <br></br>
           <% if (location.updated_at-Time.now).days.round < 0%>

             0 days ago
          <% else %>
               <%= (location.updated_at-Time.now).days.round %> days ago
          <% end %>
         </td>
        <td><%= (if location.active then "Open" else "Closed" end) %></td>
        <td>
          <p><a data-open="<%= location.id %>EditModal" >Edit</a></p>
          <div class="reveal" id="<%= location.id %>EditModal" data-reveal>
            <h3> <%= location.name %> </h3>
            <%= simple_form_for location do |l| %>

              <%= l.input :name %>
              <%= l.input :address %>
              <%= l.input :phone %>
              <%= l.input :website %>
              <%= l.input :city %>
              <%= l.input :state %>
              <%= l.input :active %>
              <%= l.button :submit %>
            <% end %>


            <button class="close-button" data-close aria-label="Close modal" type="button">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>