config/routes.rb
Rails.application.routes.draw do

  get 'secret/index'

  get 'main/index'
  get 'search' => 'main#index', as: :search
  get 'newCall' => 'main#newCall', as: :newCall
  get 'validations' => 'validations'
  get 'settings' => 'settings#index', as: :settings
  get "downloadPRC" => 'settings#downloadPRC', as: :downloadPRC
  get "changePassword" => 'settings#change', as: :passwordForm

  post "changePassword" => 'settings#change', as: :changePassword

  post 'clear_form' => 'main#clear_form', as: :clear_form
  post 'newCall' => 'main#newCall'
  post 'submit_form' => 'main#submit_form'

  root 'main#index'
  resources :items
  resources :counties
  resources :item_counties
  resources :item_locations
  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/location.rb
class Location < ApplicationRecord

  # Callbacks
  before_save :reformat_phone

  # Relationships
  has_many :item_locations, dependent: :destroy
  has_many :items, through: :item_locations
  has_many :addresses, :autosave => true, dependent: :destroy
  has_many :counties, through: :addresses

  accepts_nested_attributes_for :item_locations, reject_if: lambda { |item_location| item_location[:item_id].blank? }, allow_destroy: true
  accepts_nested_attributes_for :addresses, reject_if: lambda { |addr| addr[:address].blank? }, allow_destroy: true

  # Validations
  validates :name, presence: true
  validates :addresses, presence: true
  validates_format_of :phone, with: /\A\(?\d{3}\)?[-. ]?\d{3}[-.]?\d{4}\z/, message: "should be 10 digits (area code needed) and delimited with dashes only", allow_blank: true

  # Scopes
  scope :alphabetical , -> { order('name') }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  scope :for_county, -> (id) {joins(:addresses).where(addresses: {county_id: id})}
  scope :for_item, -> (id) {joins(:item_locations).where(item_locations: {item_id: id})}
  scope :by_county, -> {joins(:addresses).order("addresses.county_id")}
  scope :by_city, -> {joins(:addresses).order("addresses.city")}
  scope :by_zipcode, -> {joins(:addresses).order("addresses.zipcode")}
  scope :by_updated, ->  {order('updated_at')}
  scope :by_active, ->  {order('active')}

  def item_locations_for_form
    collection = item_locations.where(location_id: id)
    collection.any? ? collection : item_locations.build
  end

  def link_to_website

    if self.website && self.website.length > 5
      if self.website[0...4] == "http"
        return self.website
      else
        return "http://#{website}"
      end
    end

  end

  private




  def reformat_phone
    phone = self.phone.to_s
    phone.gsub!(/[^0-9]/,"")
    self.phone = phone
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    # @l = Location.all.to_a
    # @locations = Location.all.paginate(:page => params[:page]).per_page(20)
    # @item_locations = ItemLocation.by_item.all
    @errors = ""
    # @l = Location.all.to_a
    # @locations = Location.all.paginate(:page => params[:page]).per_page(20)
    # @item_locations = ItemLocation.by_item.all

    if params[:validate] && params[:validate] != ""
      puts "stuff"
    end
    # @locations = []
    @countyName = ""
    allLocations = Location.all
    # @items = Item.all
    # @counties = County.all
    @item_locations = ItemLocation.all
    locations = []
    if params[:county] && params[:county] != ""

      @county = County.where(name: params[:county].capitalize).first
      if not @county.nil?
        @countyName = @county.name
        @countyId = @county.id
        locations = allLocations.for_county(@countyId)
        unless locations.blank?
          locations = allLocations.for_county(@countyId)
        end

        puts @countyName
      else
        locations = allLocations
        @errors = "#{params[:county]} does not exist"
        # @locations = []

        return
      end
    else

      locations = allLocations
    end
    if params[:sortby] && params[:sortby] != ""
      sort = params[:sortby]
      if sort == "county"
        @locations = locations.by_county.alphabetical.paginate(:page => params[:page]).per_page(10)
        # @locations = locations.alphabetical.paginate(:page => params[:page]).per_page(10)
      elsif sort == "name"
        @locations = locations.alphabetical.paginate(:page => params[:page]).per_page(10)
      elsif sort == "verified"
        @locations = locations.by_updated.paginate(:page => params[:page]).per_page(10)
      elsif sort == "city"
        @locations = locations.by_city.alphabetical.paginate(:page => params[:page]).per_page(10)
      elsif sort == "zipcode"
        @locations = locations.by_zipcode.alphabetical.paginate(:page => params[:page]).per_page(10)
      elsif sort == "active"
        @locations = locations.by_active.alphabetical.paginate(:page => params[:page]).per_page(10)
      end
      puts "woah it works"

    else
      @locations = locations.alphabetical.paginate(:page => params[:page]).per_page(10)
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @item_locations = @location.item_locations.by_item.to_a
  end

  # GET /locations/new
  def new
    @location = Location.new
    @location.item_locations.build
    @location.addresses.build
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)
    puts location_params
    # @item_location.verified = Date.today
    # puts @item_location.verified
    # @item_location.context = "hullo we trying"
    # puts @item_location.context
    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|

      if @location.update(location_params)
        if params[:redirect] == "true"
          format.html { redirect_to :back, notice: 'Location was successfully validated.' }
          format.json { render :show, status: :ok, location: @location }
        else
          format.html { redirect_to @location, notice: 'Location was successfully updated.' }
          format.json { render :show, status: :ok, location: @location }
        end

      else
        @location.reload
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params

      params.require(:location).permit(:name, :phone, :website, :verified, :active, :details, addresses_attributes: [:id, :location_id, :county_id, :address, :city, :zipcode, :active, :_destroy], item_locations_attributes: [:id, :item_id, :location_id, :active, :description, :_destroy, :verified, :context])

    end
end

app/views/locations/_address_fields.html.erb
<div class="fields">
  <%= l.input :address %>
  <div class="row">
    <div class="large-4 columns">
      <%= l.input :city %>

    </div>
    <div class="large-3 columns">
      <%= l.input :zipcode %>
    </div>
    <div class="large-4 columns">
      County
      <%= l.collection_select(:county_id, County.all.alphabetical, :id, :name, :prompt => "Choose a county...") %>
    </div>
    <div class="large-1 columns">
      <%= l.link_to_remove("x") %>
    </div>

  </div>
</div>

app/views/locations/_form.html.erb
<div class='row'>
  <div class="large-8 large-centered columns">
    <fieldset>
      <%= simple_nested_form_for @location, :html => { :class => 'form-horizontal' } do |location_form| %>
      <%= location_form.input :verified, :as => :hidden, :input_html => { :value => Time.new.to_date } %>
      <% if location.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(location.errors.count, "error") %>
          prohibited this location from being saved:</h2>
        <ul>
          <% location.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <%= render :partial => "locations/location_fields", :locals => { :l => location_form } %>
      <legend>Addresses</legend>
      <div id="addresses">
        <%= location_form.simple_fields_for :addresses do |addr_f| %>
        <%= render :partial => "locations/address_fields", :locals => { :l => addr_f } %>
        <% end %>
        <p>
          <br/><%= location_form.link_to_add("Add Address", :addresses, :class => 'button tiny') %>
        </p>
      </div>
      <legend>Items</legend>
      <div id="item_locations">
        <%= location_form.simple_fields_for :item_locations do |il_form| %>
        <%= render :partial => "locations/itemLocations", :locals => { :l => il_form } %>
        <% end %>
        <p>
          <br/><%= location_form.link_to_add("Add Item", :item_locations, :class => 'button tiny') %>
        </p>
      </div>

      <%= location_form.submit nil, :class => 'button' %>
      <% end %>
    </fieldset>
  </div>
</div>

app/views/locations/_itemLocations.html.erb
<div class="row">


  <div class="large-4 columns">
    <%= l.collection_select(:item_id, Item.all.alphabetical, :id, :name, { :prompt => 'Select Item' } ) %>
  </div>
  <div class="large-6 columns">
    <%= l.text_area(:description) %>
  </div>
  <div class="large-1 columns">
    <%= l.input(:active) %>
  </div>
  <div class="large-1 columns">
    <%= l.link_to_remove("x") %>
  </div>


  <%= l.hidden_field(:verified, :value => Date.today) %>
  <%= l.hidden_field(:context, :value => "we still tryin") %>

</div>

app/views/locations/_item_checklist.html.erb
<div class='row'>
  <div class="large-8 large-centered columns">
    <fieldset>
      <%= simple_nested_form_for @location, :html => { :class => 'form-horizontal' } do |location_form| %>
      <div id="item_locations">
        <table>
          <thead>
            <tr>
              <th>Item</th>
              <th>Active</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <%= location_form.simple_fields_for :item_locations do |il_form| %>
            <tr>
              <%= render :partial => "locations/item_field", :locals => { :l => il_form } %>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <% end %>
    </fieldset>
  </div>
</div>

app/views/locations/_item_field.html.erb
<td>
  <% if !l.object.item.nil? %>

    <%= l.object.item.name %>

  <% end %>
</td>
<td>
  <%= l.input :active, label: "" %>
</td>

app/views/locations/_item_loc_active.html.erb
<div class="fields" style="display:none;">
  <div class="large-1 columns">
    <%= l.collection_select(:item_id, Item.all.alphabetical, :id, :name, { :prompt => 'Select Item' } ) %>
    <%= l.input :active %>
    <%= l.link_to_remove("x") %>
  </div>
</div>

app/views/locations/_loc_address_active.html.erb
<div class="fields" style="display:none;">
  <div class="large-1 columns">
    <%= l.collection_select(:location_id, [l.object.location], :id, :name, { :prompt => 'Select Loc' } ) %>
    <%= l.input :active %>
    <%= l.input :address %>
    <%= l.link_to_remove("x") %>
  </div>
</div>

app/views/locations/_location_fields.html.erb
<%= l.input :name %>
<%= l.input :phone %>
<%= l.input :website %>
<%= l.input :active %>
Details
<%= l.text_area :details %>

app/views/locations/edit.html.erb
<div class="large-12 columns">
  <div class="panel callout radius">
    <h2>Editing Location</h2>
    <%= render 'form', location: @location %>
  </div>
</div>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="large-1 columns">

    <h1>Locations</h1>
  </div>

  <div class="large-3 columns button-group">

    <% if params[:validate] == "true" %>
      <%= button_to "Normal Mode", locations_path,class: "button", method: :get, params: { validate: "", sortby: params[:sortby], county: params[:county] }  %>
    <% else %>
      <%= button_to "Verify Mode", locations_path,class: "button", method: :get, params: { validate: "true", sortby: params[:sortby], county: params[:county] }  %>
    <% end %>


    <%= link_to '<i class="fa fa-plus-square" aria-hidden="true"></i> Add Location'.html_safe, new_location_path,class: "button" %>


  </div>
</div>

<div class="row">
    <div class="large-6 columns button-group">
      <legend>Sort by </legend>
      <% sort = params[:sortby] %>
      <% countyClass = "secondary button" %>
      <% nameClass = "secondary button" %>
      <% verifiedClass = "secondary button" %>
      <% cityClass = "secondary button" %>
      <% activeClass = "secondary button" %>
      <% if sort == "county" %>

        <% countyClass = "button" %>
      <% elsif sort == "name" %>
        <% nameClass = "button" %>
      <% elsif sort == "verified" %>
        <% verifiedClass = "button" %>
      <% elsif sort == "city" %>
        <% cityClass = "button" %>
      <% elsif sort == "active" %>
        <% activeClass = "button" %>
      <% else %>
        <% nameClass = "button" %>
      <% end %>
      <%= button_to "Name", locations_path,  class: nameClass,  method: :get, params: {  sortby: "name", validate: params[:validate], county: params[:county] }  %>
      <%= button_to "County", locations_path, class: countyClass,  method: :get, params: {  sortby: "county", validate: params[:validate], county: params[:county] }  %>
      <%= button_to "Last Verified", locations_path,  class: verifiedClass, method: :get, params: {  sortby: "verified", validate: params[:validate], county: params[:county] }  %>
      <%= button_to "City", locations_path,  class: cityClass, method: :get, params: {  sortby: "city", validate: params[:validate], county: params[:county] }  %>
      <%= button_to "Active", locations_path,  class: activeClass, method: :get, params: {  sortby: "active", validate: params[:validate], county: params[:county]}  %>

    </div>

  <%= form_tag("", :method => "get", id: "search-form") do %>
    <fieldset class="large-6 columns">
        <script>
        $( function() {
          $( "#tags" ).autocomplete({
            source: '<%= counties_path(:json) %>'
          });
        } );
        </script>
        <div class="ui-widget">
          <legend>Filter by </legend>
          <div class="filter">
            <div class="large-6 columns">
              <input id="tags" type="text" name="county" placeholder = 'Enter County' value='<%= params[:county] if params[:county]%>'>
              <input style="display: none" name="validate" value='<%= params[:validate] if params[:validate]%>'>
              <input style="display: none" name="sortby" value='<%= params[:sortby] if params[:sortby]%>'>
            </div>
            <div class="small-6 columns">
              <%= submit_tag "Search", :name => nil, class: "button" %>
            </div>
          </div >
        </div>
    </fieldset>
  <% end %>
</div>
</div>
<div class="row" >
<%= button_to "Clear Filters", locations_path,class: "alert button", method: :get, params: { validate: params[:validate], sortby: "", county: ""} %>
</div>

<div class="expanded row" style="width: 90%;">

  <div class="panel">
    <% if @errors != "" %>
      <div class="small-3 small-centered columns">
        <h5> <%= @errors %> </h5>
      </div>

    <% else %>
      <% if @locations == [] %>
        <div class="small-3 small-centered columns">
          <h5> <%= params[:county] %> has no locations right now. </h5>
        </div>
      <% else %>
        <% if params[:county] && params[:county] != "" %>
          <h5> <%= params[:county].capitalize %> County </h5>
        <% end %>
        <table border= "1px solid black">
          <thead>
            <tr>
              <th>Name</th>
              <th>Address</th>
              <th>Contact Info</th>
              <th width="18%;">Items</th>
              <th width="7%;">Active</th>
              <th width="8%;">Last Verified</th>
              <th>Edit</th>
            </tr>
          </thead>
          <tbody>
            <% @locations.each do |location| %>
                <%= simple_nested_form_for location, :html => { :class => 'form-horizontal' } do |f| %>
                  <%= f.input :verified, :as => :hidden, :input_html => { :value => Time.new.to_date } %>
                <tr>
                  <td><%= link_to location.name, location, target: :_blank %></td>
                  <td>
                    <ul class="tabs" data-tabs id="example-tabs">
                      <% count = 0 %>
                      <% location.counties.distinct.each do |county| %>
                        <% if count == 0 %>
                          <li class="tabs-title is-active"><a href="#<%= "panel#{count}-#{location.id}" %>" aria-selected="true"><%= county.name %></a></li>
                        <% else %>
                          <li class="tabs-title"><a href="#<%= "panel#{count}-#{location.id}" %>"><%= county.name %></a></li>
                        <% end %>
                        <% count += 1 %>
                      <% end %>
                    </ul>

                    <div class="tabs-content" data-tabs-content="example-tabs">
                      <% count = 0 %>
                      <% location.counties.distinct.each do |county| %>
                        <% shouldDisplay = " is-active" %>
                        <% if count != 0 %>
                          <% shouldDisplay = "" %>
                        <% end %>
                            <div class="tabs-panel<%=shouldDisplay%>" id="<%= "panel#{count}-#{location.id}" %>">
                              <ul>
                              <% if params[:validate] && params[:validate] != "" %>
                                  <% count1 = 0 %>
                                  <%= f.simple_fields_for :addresses do |addrForm| %>
                                    <% if addrForm.object.county.id == county.id %>
                                      <%= render :partial => "locations/loc_address_active", :locals => { :l => addrForm } %>
                                      <%= addrForm.input :active, label: addrForm.object.full_address, input_html: { id: "addressForm#{location.id}#{count1}" }%>
                                    <% end %>
                                    <% count1 += 1 %>
                                  <% end %>
                              <% else %>
                                <% location.addresses.for_county(county.id).each do |addr| %>
                                  <li><%= link_to addr.full_address, "http://maps.google.com/?q=#{addr.full_address}", target: :_blank %></li>
                                <% end %>
                              <% end %>
                              </ul>
                            </div>
                        <% count += 1 %>
                      <% end %>
                    </div>
                 </td>

                  <td>
                    <%= link_to location.website, "#{location.link_to_website}", target: :_blank %> <br/>

                    <%= number_to_phone location.phone %>
                  </td>
                  <td>
                    <% if params[:validate] && params[:validate] != "" %>
                      <% count = 0 %>
                      <%= f.simple_fields_for :item_locations do |il| %>
                        <%= render :partial => "locations/item_loc_active", :locals => { :l => il } %>

                        <%= il.input :active, label: il.object.item.name.capitalize, input_html: { id: "itemcheck#{location.id}#{count}" }%>
                        <% count += 1 %>
                      <% end %>
                    <% else %>
                      <% @item_locations.for_location(location.id).each do |il| %>
                        <%= il.item.name.capitalize %> <br/>
                      <% end %>
                    <% end %>
                  </td>

                    <td>
                      <% if params[:validate] && params[:validate] != "" %>
                        <%= f.input :active, label: "",  as: :radio_buttons, :collection => [['Active', true],['Inactive', false]], :input_html => {  id: "active#{location.id}" }  %>
                      <% else %>
                        <%= location.active ? "Active" : "Inactive" %>
                      <% end %>
                    </td>
                    <td>
                      <% if (Time.new.to_date - location.updated_at.to_date).to_i < 0%>
                      0 days ago
                      <% elsif (Time.new.to_date - location.updated_at.to_date).to_i == 1 %>
                        1 day ago
                      <% else %>
                        <%= (Time.new.to_date - location.updated_at.to_date).to_i %> days ago
                      <% end %>
                    </td>
                    <td>
                      <% if params[:validate] && params[:validate] != "" %>
                        <%= hidden_field_tag(:redirect, 'true') %>
                        <%= f.submit "Verify", class: "button radius" %>
                        <%= link_to 'Edit', edit_location_path(location), target: :_blank %>
                      <% else %>
                        <%= link_to 'Edit', edit_location_path(location), target: :_blank %>
                      <% end %>
                    </td>
                  <% end %>
                </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    <% end %>


  </div></div>
  <div class="row">
    <% if @errors == "" %>
      <%= will_paginate @locations, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
    <% end %>
  </div>
  <br>

app/views/locations/new.html.erb
<div class="large-12 columns">
  <div class="panel callout radius">
    <h2>New Location</h2>
    <%= render 'form', location: @location %>
  </div>
</div>

app/views/locations/show.html.erb
<div class="large-8 large-centered columns">
  <div class="panel callout radius">
    <p id="notice"><%= notice %></p>
    <h3><%= @location.name %></h3>
    <p>
      <strong>Addresses:</strong>
      <% @addresses = @location.addresses %>
      <ol>
        <% count = 0 %>
        <% @addresses.each do |a| %>
        <% count += 1 %>
        <% if count != @addresses.size %>
        <li><%= link_to a.full_address, "http://maps.google.com/?q=#{a.full_address}", target: :_blank %>
          <br></br>
        </li>
      <% else %>
        <li><%= link_to a.full_address, "http://maps.google.com/?q=#{a.full_address}", target: :_blank %>
        </li>
        <% end %>
        <%end%>
      </ol>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= number_to_phone(@location.phone, area_code: true) %>
    </p>

    <p>
      <strong>Website:</strong>
      <%= link_to @location.website, "#{@location.link_to_website}", target: :_blank %>
    </p>

    <p>
      <strong>Active:</strong>
      <%= @location.active ? "Yes" : "No" %>
    </p>

    <p>
      <strong>Details:</strong>
      <%= @location.details %>
    </p>

    <br>
    <h5>Items</h5>
    <table>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Active</th>
      </tr>
      <% for il in @item_locations %>
      <tr>
        <td><%= il.item.name.titleize%></td>
        <td><%=il.description.nil? ? "None" : il.description %></td>
        <td><%= il.active ? "Active" : "Inactive" %></td>
      </tr>
      <% end %>
    </table>
  </p>

  <div class="row">
    <%= link_to "Edit #{@location.name}", edit_location_path(@location), class: "button" %>
    <%= link_to 'See All Locations', locations_path, class: "button" %>
    <%= link_to 'Delete', location_path(@location), method: 'delete', class: "alert button" %>
  </div>

</div>
</div>